### ISSUE TITLE
Infinite Craft Decraft Exploit

### ISSUE THREAD

**Issue by Foxersthe** [VolmitSoftware/Adapt#116]
You can get an infinite amount of crafting xp by crafting items such as blocks that can be crafted back, then repeat.

**Comment by NextdoorPsycho** [comment]
If im not mistalken you should only get  back LESS blocks that you put in. What were you doing to be able to  do it infinitely

**Comment by Foxersthe** [comment]
For example you take 9 emeralds and make it into a block, then back into 9 emeralds, and repeat and you still get the crafting xp for it.

**Comment by NextdoorPsycho** [comment]
Have you used the skill?

**Comment by NextdoorPsycho** [comment]
There is literally no possible way that you can duplicate because i only am giving the player like half of the returned total. Yea you can do it for a while, but like. if you are losing 50% of the returns that really limits your gains 

https://user-images.githubusercontent.com/29320316/189039780-2d4cc3e9-3a4b-40e7-bce7-aa6ccbec0b5d.mp4
