### ISSUE TITLE
Automatically download language file from GitHub

### ISSUE THREAD

**Issue by poikcue** [VolmitSoftware/Adapt#130]
In some cases (e.g. when a new version of Adapt is released and the English language files happen to be updated) the translation of some Adapt language files is not updated in time. Here is an idea for automatic updating of the language files:
1. check if the "language" key in the configuration file is en_US. if so, use the language integrated by the plugin.
2. check if the language folder has the specified language. If so, use the local language file.
3. Try to download the specified language from the repository https://github.com/VolmitSoftware/Adapt/raw/main/src/main/resources/(language).json
4. If server can't download it (no file specified or can't connect to github), try to search for the existence of the language file in the jar file.

I'm not sure if the java language supports doing this, but this seems to keep the language files up to date.

**Comment by Armin231** [comment]
Afaik adapt generates the language files from the jar

**Comment by NextdoorPsycho** [comment]
Ill say this is 50% done, this is something i wanted to do. but the language system was slapped on last minute so i never got time to do this. but this is something i wanted to do. but the problem is when i update / if i modify the language file structure. the old Jars get ruined. so id need to be careful, and for now in-app localization is the "best" solution as of now
