### ISSUE TITLE
Support for disabled skills

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#189]
### Adding, Removing, or Changing

Changing

### Type of Modification

I want to support disabled skills more

### What are you trying to modify

The way I would implement this is checking whther a skill is disabled / enabled, then load playerdata etc. after that. If a skill is disabled the playerdata should be skipped and not trying to get loaded which doesnt seem to happen right now since disabled skills still throw errors even if disabled. I think if a skill is marked as disabled it should just be completely ignored by anything.

### Alternatives

Disabling singular adaptations which isnt really a solution since some servers might just not want certain skills at all, so if you just disable all adaptations the skill still levels.

**Comment by NextdoorPsycho** [comment]
Fixed on Dev branch. 
You may Disable skills, But if you disable a skill a player has then they will lose all data pertaining to that. HOWEVER
You can still disable it without errors, and you can enable it later. If you have any errors its probably because the Adapt Hotloader is broken, thats an issue in it of itself, and you can resolve this by either using Biletoold to reload the plugin, or restarting the server. either way you are able to disable / enable Skills now
