### ISSUE TITLE
Not compatible with Lands plugin

### ISSUE THREAD

**Issue by toonystank** [VolmitSoftware/Adapt#256]
### Problem

I use `Lands` plugin for anti-grief. people make claims and protect their stuff but with some skills, the claim protection is ignored

### Tested skills

- Can attack players/mobs inside a claim that you don't have access with poisoned and bloody blades. this only applies the appropriate potion effect and players take damage from it
- Axe chop skill lets you cut trees on claims that you don't have access

### More info

I saw that event `PlayerInteractEvent` is used here. There are no checks for Claim protection plugins in the code to my knowledge. and the #isCancelled() method is Deprecated

### Minecraft Version

1.19.2

### Adapt Version

1.4.2-1.19.2

### Log

https://mclo.gs/VughRJW

**Comment by doitliketyler** [comment]
+1

**Comment by NextdoorPsycho** [comment]
the isCanceled method is deprecated not because it does not work but there are 2 possibilities of what can be canceled. and will return true (was canceled) if ANYTHING in that was canceled. Deprecation in spigot is pointless. like Async is deprecated, not because its not working but because its confusing and could be confused with "A, Sync function"  and not " an Async function"

If the plugin is not canceling that method however I can try making a PR into that or looking into it

**Comment by NextdoorPsycho** [comment]
> +1

Don't write +1, hit the 👍 thing on the post, that way its actually counted and not emailing everyone

**Comment by NextdoorPsycho** [comment]
I think I added it properly with the requireWorldguardBuildPermToUseAdaptations setting, it asks WorldGuard if the player can build where the player is and if they can, they can use abilities. I still need to test it tho

**Comment by NextdoorPsycho** [comment]
ok After Testing this works with WorldGuard Regions

I don't know how I feel about going through EVERY CLAIMING PLUGIN ever created and adding support for the niche ones. Having said that, If they are using World guard as a core, then This works with that now by default if you deny build.

IF NOT however, please make a new issue and justify why I need to support this plugin etc... or how I can add it / a docs link etc...

**Comment by toonystank** [comment]
Works with the `Lands` plugin i use
