### ISSUE TITLE
More control over sources of experience

### ISSUE THREAD

**Issue by doitliketyler** [VolmitSoftware/Adapt#261]
### Adding, Removing, or Changing

Adding

### Type of Modification

More config options to control the sources of experience

### What are you trying to modify

Currently, unless completely disabled, when you consume food you gain exp for Herbalism...which is mostly ok until players discover you can infinitely drink milk and just gain herbalism XP. This gets worse when someone afk's in front of a cow using an autoclicker. Would be nice if milk was completely removed from Herbalism or there were more options in general to control the sources of where exp is coming from.

**Comment by NextdoorPsycho** [comment]
I can fix that too. 
This is **NOT** a Build your own skills plugin. Having said that, if you find Exploits I'll TOTALLY Fix it. like Milk/Water I see that being an issue and I'll patch it out. and if I were to make every source of food, block, time, status, potion, location, weapon, and enchantment etc configurable that would only fit a niche / be a waste of everyone's time. 

But this in specific I can fix that!, and I'll add a cooldown on that rn. you CAN however modify how much XP is gained from These Sources:
<img width="437" alt="CleanShot 2022-10-07 at 14 40 08@2x" src="https://user-images.githubusercontent.com/29320316/194662876-74c0bdfe-e9fa-4ef1-9fbc-c3a1d2a6cf10.png">
So that should be enough generic for people. but being able to infinitely drink milk is not ok. and I'll fix that. 
Thank you for the report

**Comment by NextdoorPsycho** [comment]
Added to the Herbalism cooldown, thank you!

**Comment by doitliketyler** [comment]
Awesome. Totally understand and that works for me. Thank you!
