### ISSUE TITLE
Remote access skill portkey throws as enderpearl and does not function as intended.

### ISSUE THREAD

**Issue by MisterEpic** [VolmitSoftware/Adapt#416]
### Problem

Here is a video example - https://medal.tv/games/minecraft/clips/15tw3AgkRWfqCj/XJw82Cg3Nlkc?invite=cr-MSxMOG0sNjcxOTk1OTcs 
The player tried to bind the item to a chest before that and it also would not work.

### Minecraft Version

1.19.2

### Adapt Version

1.6.2

### Log

No errors or logs

**Comment by NextdoorPsycho** [comment]
that us quite a few versions ago, and Spigot had an issue in it back then, For example the same issue will happen with EyeOfEnder's that are bound recall points, there was no fix at the time. until the game updated, and I've fixed it since then / added other fixes on latest to mitigate that, are you not able to update?

**Comment by NextdoorPsycho** [comment]
as this IS fixed on latest i will be closing this
